# Do NOT update manually; changes here will be overwritten by Copier
<<<<<<< HEAD
_commit: v1.1.4
=======
_commit: v1.1.3
>>>>>>> 8b856dc... [DCK] Copier update to v1.1.3
_src_path: gh:oca/oca-addons-repo-template
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: OCA modules for DMS
repo_name: Document Management System modules for Odoo
repo_slug: dms
travis_apt_packages: []
travis_apt_sources: []
